# Generated by Django 3.1.1 on 2020-10-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
