# Generated by Django 3.1.1 on 2020-09-27 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='originalbasket',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userorders',
            name='stripepid',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='singleorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singleorderitems', to='checkout.userorders'),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='finaltotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='userorders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
