# Generated by Django 3.1.1 on 2020-09-27 15:15

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200927_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorders',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
