# Generated by Django 3.1.1 on 2020-09-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
        ('checkout', '0003_auto_20200927_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorders',
            name='userprofile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='userprofiles.userprofile'),
        ),
    ]
